### ISSUE TITLE
How to run cpp after installing package in atom

### ISSUE THREAD

**Issue by scheung38** [jbw3/language-cpp14#1]
How to run and debug simple Hello World.cpp files after installing cpp14 package? Do I need to setup other dependencies?

```
#include <iostream>

using namespace std;

int main(int argc, char* argv[])
{
    cout <<"Hey, you, I'am alive! Ohn and Hello World!\n";
    cin >> ;;
    return 0;
}
```

How to run it in atom? I don't see Make or Run button anywhere? Many thank.

**Comment by jbw3** [comment]
Hi,

language-cpp14 is a package for C++ syntax highlighting. It can not currently build or run programs. However, there are probably other packages available to do this.

Thanks!
