### ISSUE TITLE
Syntax highlighting slightly diminished?

### ISSUE THREAD

**Issue by adrian5** [jbw3/language-cpp14#6]
When using this package, my syntax loses some fidelity (appears less colorful). Is there a possibility to retain the selectors from the regular C++ package shipping with Atom, while extending the feature set to C++14?

I think the changes are:
- local variables and class methods now have the same color
- class member variables have no distinguishing color, i.e. are "default" colored (grey in my case)

**Comment by jbw3** [comment]
I don't know of a way to extend one syntax package with another. Could you post some example code demonstrating the differences you are seeing?

**Comment by adrian5** [comment]
Here two screenshots comparing the regular _C++_ and the _C++14_ plugin:
![c](https://cloud.githubusercontent.com/assets/5426924/14440579/cecf1336-0030-11e6-878a-971f94dcd3cc.png)
![c 14](https://cloud.githubusercontent.com/assets/5426924/14440580/ced08d6a-0030-11e6-9cce-6ab1ab2e0978.png)

I think the default highlighting isn't even entirely consistent, but with the complexity of C++, I tend to welcome any means of visual separation within the code. If in fact, you consider your plugin be more sensible in its distinction of elements, then I certainly respect that. It does fix the highlighting issues it's supposed to.

**Comment by jbw3** [comment]
You're right that it can be difficult to be completely consistent when highlighting C++, but I can see how these additions, especially highlighting the member variables, would be nice. I will keep this in mind for future improvements.
