### ISSUE TITLE
Syntax highlighting fails after first usage of template template parameters

### ISSUE THREAD

**Issue by engelphi** [jbw3/language-cpp14#8]
As can be seen in the attached pictured the syntax highlighting partially fails after using template template parameters. This can be seen especially in the second variant of the filter function. The function declaration is completely uncolored.

Checked with all syntax themes that are installed by default.

![screenshot](https://cloud.githubusercontent.com/assets/19877419/16038600/092cdd2a-3226-11e6-8c3c-93ae5c98af4f.png)

**Comment by jplatte** [comment]
This also happens when the template keyword is used as a disambiguator for dependent names (see [cppreference](http://en.cppreference.com/w/cpp/language/dependent_name#The_template_disambiguator_for_dependent_names)).

**Comment by jbw3** [comment]
@engelphi This should be fixed with the 0.6.2 release.
@jplatte I've created a separate issue for the bug you found (#9).

**Comment by jplatte** [comment]
@jbw3 Thanks for the great work!
